CREATE TABLE IF NOT EXISTS print_agents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agent_uid VARCHAR(120) NOT NULL,
    client_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NOT NULL,
    display_name VARCHAR(150) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    platform VARCHAR(30) DEFAULT NULL,
    version VARCHAR(40) DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    last_seen_at DATETIME DEFAULT NULL,
    last_error VARCHAR(190) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_print_agents_uid (agent_uid),
    KEY idx_print_agents_client_branch (client_id, branch_id),
    KEY idx_print_agents_status (status),
    CONSTRAINT fk_print_agents_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_print_agents_branch FOREIGN KEY (branch_id) REFERENCES client_branches(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS print_jobs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    job_uid VARCHAR(120) NOT NULL,
    request_uid VARCHAR(120) NOT NULL,
    client_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NOT NULL,
    target_agent_id BIGINT UNSIGNED DEFAULT NULL,
    source_type VARCHAR(40) NOT NULL DEFAULT 'sale',
    source_uid VARCHAR(120) DEFAULT NULL,
    document_type VARCHAR(40) NOT NULL DEFAULT 'ticket',
    payload_json LONGTEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    claimed_by_agent_id BIGINT UNSIGNED DEFAULT NULL,
    claimed_at DATETIME DEFAULT NULL,
    lease_until DATETIME DEFAULT NULL,
    claim_token_hash CHAR(64) DEFAULT NULL,
    printed_at DATETIME DEFAULT NULL,
    result_json LONGTEXT DEFAULT NULL,
    last_error VARCHAR(190) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_print_jobs_uid (job_uid),
    UNIQUE KEY uq_print_jobs_request (client_id, request_uid),
    KEY idx_print_jobs_poll (client_id, branch_id, status, available_at),
    KEY idx_print_jobs_agent (target_agent_id, status, available_at),
    KEY idx_print_jobs_source (client_id, source_type, source_uid),
    CONSTRAINT fk_print_jobs_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_print_jobs_branch FOREIGN KEY (branch_id) REFERENCES client_branches(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_print_jobs_target_agent FOREIGN KEY (target_agent_id) REFERENCES print_agents(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_print_jobs_claimed_agent FOREIGN KEY (claimed_by_agent_id) REFERENCES print_agents(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
